apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-python-config
  namespace: devops
  labels:
    app: devops-python
data:
  PORT: "5000"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  SERVICE_NAME: "devops-info-service"
