{{- if .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "devops-app.fullname" . }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "devops-app.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.statefulset.updateStrategy }}
  updateStrategy:
    {{- toYaml .Values.statefulset.updateStrategy | nindent 4 }}
  {{- end }}
  {{- if .Values.statefulset.podManagementPolicy }}
  podManagementPolicy: {{ .Values.statefulset.podManagementPolicy }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.configFile.enabled }}
        checksum/config-file: {{ include (print $.Template.BasePath "/configmap-file.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.secrets.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- include "devops-app.vaultAnnotations" . | nindent 8 }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "devops-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "devops-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers.enabled }}
      initContainers:
        {{- include "devops-app.initContainers" . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        {{- include "devops-app.envVars" . | nindent 8 }}
        {{- if .Values.configMap.enabled }}
        envFrom:
        - configMapRef:
            name: {{ include "devops-app.fullname" . }}
        {{- end }}
        {{- if .Values.secrets.enabled }}
        - secretRef:
            name: {{ include "devops-app.fullname" . }}-secret
        {{- end }}
        volumeMounts:
        {{- if .Values.configFile.enabled }}
        - name: config-volume
          mountPath: /config
          readOnly: true
        {{- end }}
        - name: data
          mountPath: /data
        {{- if and .Values.initContainers.enabled .Values.initContainers.download.enabled }}
        - name: workdir
          mountPath: /data/downloaded
          readOnly: true
        {{- end }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.configFile.enabled }}
      - name: config-volume
        configMap:
          name: {{ include "devops-app.fullname" . }}-config-file
      {{- end }}
      {{- if and .Values.initContainers.enabled .Values.initContainers.download.enabled }}
      - name: workdir
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        {{- include "devops-app.labels" . | nindent 8 }}
    spec:
      accessModes: 
        {{- toYaml .Values.statefulset.volumeClaimTemplates.accessModes | nindent 8 }}
      {{- if .Values.statefulset.volumeClaimTemplates.storageClassName }}
      storageClassName: {{ .Values.statefulset.volumeClaimTemplates.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.statefulset.volumeClaimTemplates.storage }}
{{- end }}
